# Generated by Django 4.2.1 on 2024-01-11 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
